### ISSUE TITLE
[beta bug] iOS 14 keyboard safe area displaces cells

### ISSUE THREAD

**Issue by apptekstudios** [apptekstudios/ASCollectionView#169]
**Describe the bug**
In iOS14(b4) the new keyboard safe area displaces cells when the keyboard is open, leading to strange layout behaviours.

https://openradar.appspot.com/radar?id=4929616280027136
https://twitter.com/tobeasbrennan/status/1292226699782844416

**Comment by DenTelezhkin** [comment]
I believe this is not only beta bug, as this is happening on iOS 14.1 as well.

**Comment by zntfdr** [comment]
Not sure if it works for this library, but in my case I fixed this issue by swizzling `UIHostingController`'s `keyboardWillShowWithNotification:` private API as shown by @steipete [here](https://steipete.me/posts/disabling-keyboard-avoidance-in-swiftui-uihostingcontroller/).

Note that the bug is fixed in iOS 14.2 (without swizzling), therefore the patch above should be used only for iOS 14.0-14.1

**Comment by apptekstudios** [comment]
Thanks @zntfdr!

@DenTelezhkin this is actually fixed on the v1.8 branch, unfortunately I haven’t had time to finish updating docs and move it into master yet but it is stable and ready to use :)

**Comment by DenTelezhkin** [comment]
Thanks @apptekstudios!

1.8 branch works in my case.

**Comment by skunkworker** [comment]
Hi, I am using the v1.8.0WIP branch and still seeing this. Attached is a screen recording of the behavior. The lowest 3 cells seem to "load in" from a corner once the card over view is dismissed with the keyboard.

[ascollectionview_bug.mov.zip](https://github.com/apptekstudios/ASCollectionView/files/5550666/ascollectionview_bug.mov.zip)
